"""Real Initial Create

Revision ID: 19ffcf5b4fe3
Revises: 
Create Date: 2026-01-31 05:06:20.312159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '19ffcf5b4fe3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chunk_timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decisions_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_chunk_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('child_chunk_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_year'), 'events', ['year'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('drive_id', sa.String(length=255), nullable=False),
    sa.Column('drive_name', sa.String(length=500), nullable=False),
    sa.Column('drive_path', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('gcs_url', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.Enum('GOOGLE_DOC', 'GOOGLE_SHEET', 'GOOGLE_FORM', 'PDF', 'DOCX', 'XLSX', 'PPTX', 'HWP', 'OTHER', name='document_type'), nullable=False),
    sa.Column('doc_category', sa.Enum('MEETING_DOCUMENT', 'WORK_DOCUMENT', 'OTHER_DOCUMENT', name='document_category'), nullable=False),
    sa.Column('meeting_subtype', sa.Enum('AGENDA', 'MINUTES', 'RESULT', 'OTHER', name='meeting_subtype'), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.Column('standardized_name', sa.String(length=500), nullable=True),
    sa.Column('time_decay_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLASSIFYING', 'PARSING', 'PREPROCESSING', 'CHUNKING', 'EMBEDDING', 'COMPLETED', 'FAILED', name='document_status'), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('preprocessed_content', sa.Text(), nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_access_level'), 'documents', ['access_level'], unique=False)
    op.create_index(op.f('ix_documents_doc_category'), 'documents', ['doc_category'], unique=False)
    op.create_index(op.f('ix_documents_drive_id'), 'documents', ['drive_id'], unique=True)
    op.create_index(op.f('ix_documents_event_id'), 'documents', ['event_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_time_decay_date'), 'documents', ['time_decay_date'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_link', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_references_event_id'), 'references', ['event_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_chunk_id', sa.Integer(), nullable=True),
    sa.Column('is_parent', sa.Boolean(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_content', sa.Text(), nullable=True),
    sa.Column('section_header', sa.String(length=500), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_access_level'), 'document_chunks', ['access_level'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_is_parent'), 'document_chunks', ['is_parent'], unique=False)
    op.create_index(op.f('ix_document_chunks_parent_chunk_id'), 'document_chunks', ['parent_chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_parent_chunk_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_is_parent'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_access_level'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_references_event_id'), table_name='references')
    op.drop_table('references')
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_time_decay_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_event_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_drive_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_access_level'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_events_year'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
