"""Initial migration

Revision ID: f6cdfd68914e
Revises: 
Create Date: 2026-01-31 04:58:48.358233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6cdfd68914e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('parent_chunk_id', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('is_parent', sa.Boolean(), nullable=False))
    op.add_column('document_chunks', sa.Column('parent_content', sa.Text(), nullable=True))
    op.add_column('document_chunks', sa.Column('section_header', sa.String(length=500), nullable=True))
    op.add_column('document_chunks', sa.Column('access_level', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('start_char', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('end_char', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_document_chunks_access_level'), 'document_chunks', ['access_level'], unique=False)
    op.create_index(op.f('ix_document_chunks_is_parent'), 'document_chunks', ['is_parent'], unique=False)
    op.create_index(op.f('ix_document_chunks_parent_chunk_id'), 'document_chunks', ['parent_chunk_id'], unique=False)
    op.create_foreign_key(None, 'document_chunks', 'document_chunks', ['parent_chunk_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('event_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('gcs_url', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('doc_category', sa.Enum('MEETING_DOCUMENT', 'WORK_DOCUMENT', 'OTHER_DOCUMENT', name='document_category'), nullable=False))
    op.add_column('documents', sa.Column('meeting_subtype', sa.Enum('AGENDA', 'MINUTES', 'RESULT', 'OTHER', name='meeting_subtype'), nullable=True))
    op.add_column('documents', sa.Column('access_level', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('standardized_name', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('time_decay_date', sa.Date(), nullable=True))
    op.add_column('documents', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('preprocessed_content', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('current_step', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_access_level'), 'documents', ['access_level'], unique=False)
    op.create_index(op.f('ix_documents_doc_category'), 'documents', ['doc_category'], unique=False)
    op.create_index(op.f('ix_documents_event_id'), 'documents', ['event_id'], unique=False)
    op.create_index(op.f('ix_documents_time_decay_date'), 'documents', ['time_decay_date'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.create_foreign_key(None, 'documents', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_time_decay_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_event_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_access_level'), table_name='documents')
    op.drop_column('documents', 'current_step')
    op.drop_column('documents', 'preprocessed_content')
    op.drop_column('documents', 'year')
    op.drop_column('documents', 'department')
    op.drop_column('documents', 'time_decay_date')
    op.drop_column('documents', 'standardized_name')
    op.drop_column('documents', 'access_level')
    op.drop_column('documents', 'meeting_subtype')
    op.drop_column('documents', 'doc_category')
    op.drop_column('documents', 'gcs_url')
    op.drop_column('documents', 'event_id')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_parent_chunk_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_is_parent'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_access_level'), table_name='document_chunks')
    op.drop_column('document_chunks', 'end_char')
    op.drop_column('document_chunks', 'start_char')
    op.drop_column('document_chunks', 'access_level')
    op.drop_column('document_chunks', 'section_header')
    op.drop_column('document_chunks', 'parent_content')
    op.drop_column('document_chunks', 'is_parent')
    op.drop_column('document_chunks', 'parent_chunk_id')
    # ### end Alembic commands ###
